## **Creando lista de 10 elementos**

In [2]:
import numpy as np

lista = list(range(1,11))
lista


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

<h1 style="color:red"><b>Transformando lista en array<h1>

In [3]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el tipo de estructura**

In [4]:
type(arreglo)

numpy.ndarray

## **Corroborando el tipo de datos de arreglo**


In [5]:
arreglo.dtype

dtype('int32')

## **Definiendo el Array de int32 a float32**

In [6]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32**

In [7]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando los datos de int32 a float32**

In [8]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Tambien existe una funcion similar a range pero en array**

In [9]:
arreglonuevo= np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Obteniendo el promedio del array**

In [10]:
promedio = np.mean(arreglo)
promedio

5.5

## **Obteniendo la mediana del array** 

In [11]:
mediana= np.median(arreglo)

## **Desviación estandar del Arreglo**

In [12]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

## **Generación de un arreglo de 10 elementos de solo unos**

In [13]:
solo1= np.repeat(1,10)
arreglo_de_unos= np.ones(10)
solo1
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **Generación de un arreglo de 10 elementos de solo unos**


In [14]:
solo0 = np.zeros(10)
solo0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## **Transformando el arreglo de unos de punto flotante a enteros**


In [15]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## **Generando arreglo aleatorio de 5 elementos**

In [16]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.38440728, 0.19884746, 0.23055818, 0.18586545, 0.44571302])

## **Generando una matriz aleatoria**

In [17]:
matriz = np.random.rand(3,3)
matriz

array([[0.06854785, 0.53714675, 0.53885787],
       [0.01154041, 0.80829461, 0.07169723],
       [0.5109768 , 0.6513708 , 0.83772194]])

## **Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5**

In [18]:
arreglo_aleat2 = np.random.randint(1,50,5)
arreglo_aleat2

array([27,  2,  7,  9, 40])

## **Generando una matriz aleatoria de 10 numeros enteros del 1 al 100**

In [19]:
matriz2 = np.random.randint(10,100,(15,15))
matriz2


array([[98, 99, 47, 17, 88, 93, 41, 33, 28, 26, 90, 54, 45, 50, 27],
       [48, 83, 54, 38, 34, 56, 74, 62, 13, 26, 38, 33, 90, 89, 87],
       [22, 31, 13, 58, 51, 51, 36, 88, 27, 67, 56, 88, 83, 17, 92],
       [36, 43, 55, 17, 35, 55, 78, 88, 86, 64, 89, 70, 89, 12, 12],
       [14, 74, 16, 55, 43, 28, 20, 97, 71, 33, 76, 46, 85, 72, 46],
       [15, 76, 14, 58, 99, 52, 66, 13, 48, 34, 62, 22, 75, 95, 93],
       [60, 54, 37, 54, 69, 20, 63, 41, 64, 10, 39, 50, 51, 55, 44],
       [94, 22, 91, 73, 96, 42, 96, 47, 86, 89, 27, 22, 61, 14, 21],
       [11, 22, 68, 57, 73, 34, 82, 37, 36, 39, 83, 93, 69, 70, 69],
       [17, 54, 42, 41, 48, 30, 45, 32, 90, 16, 15, 97, 58, 71, 28],
       [51, 49, 20, 30, 62, 38, 56, 41, 47, 63, 69, 57, 95, 72, 76],
       [38, 43, 91, 90, 84, 22, 66, 25, 80, 47, 44, 41, 93, 43, 35],
       [98, 86, 53, 32, 94, 17, 83, 91, 75, 41, 38, 95, 47, 45, 58],
       [78, 15, 99, 83, 49, 98, 30, 50, 92, 98, 55, 29, 23, 45, 48],
       [96, 57, 58, 49, 63, 97, 75