In [101]:
import numpy as np

<h1> <b> 01 - ARRAYS <h1>
<Image src="assets/licensed-image.jpg"  width=30%> 
</Image>

## **Creando lista de 10 elementos**

In [102]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

<h1 style="color:skyblue"><b>Transformando lista en array<h1>


In [103]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Corroborando el tipo de estructura**

In [104]:
type(arreglo)

numpy.ndarray

## **Corroborando el tipo de datos de arreglo**


In [105]:
arreglo.dtype

dtype('int32')

## **Definiendo el Array de int32 a float32**

In [106]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Sigue siendo un array de int32**

In [107]:
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Transformando los datos de int32 a float32**

In [108]:
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

## **Tambien existe una funcion similar a range pero en array**

In [109]:
arreglonuevo= np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## **Arreglo de 2 en 2 en Arange**

In [110]:
arreglonuevo2= np.arange(1,101,2)
arreglonuevo2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## **Obteniendo el promedio del array**

In [111]:
promedio = np.mean(arreglo)
promedio

5.5

## **Obteniendo la mediana del array** 

In [112]:
mediana= np.median(arreglo)

## **Desviación estandar del Arreglo**

In [113]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

## **Generación de un arreglo de 10 elementos de solo unos**

In [114]:
solo1= np.repeat(1,10)
arreglo_de_unos= np.ones(10)
solo1
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## **Generación de un arreglo de 10 elementos de solo ceros**


In [115]:
solo0 = np.zeros(10)
solo0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## **Transformando el arreglo de unos de punto flotante a enteros**


In [116]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## **Generando arreglo aleatorio de 5 elementos**

In [117]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.35187488, 0.61092151, 0.17017082, 0.22664341, 0.04699597])

## **Generando una matriz aleatoria**

In [118]:
matriz = np.random.rand(3,3)
matriz

array([[0.0441102 , 0.99454326, 0.01514617],
       [0.05887628, 0.95550231, 0.59807833],
       [0.10052583, 0.01481706, 0.76229694]])

## **Generando un arreglo aleatorio de 10 numeros enteros del 1 al 5**

In [119]:
arreglo_aleat2 = np.random.randint(1,100,5)
arreglo_aleat2

array([83, 99, 97, 59, 92])

## **Generando una matriz aleatoria de 10 numeros enteros del 1 al 100**

In [120]:
matriz2 = np.random.randint(10,50,(5,5))
matriz2

array([[33, 18, 46, 13, 36],
       [35, 25, 20, 13, 13],
       [10, 48, 11, 38, 44],
       [31, 47, 19, 10, 14],
       [37, 24, 28, 45, 48]])